# update on 2022.4.6
Django: 3.2.12 # 4.0.2部分第三方库未支持
django-jazzmin: 2.5.0  # NOTE: 需要手动更新
django-haystack: 3.1.1 # NOTE: 仍存在错误

django-qiniu-storage: 7.5.0 # NOTE: 已停止维护
django-crontab: 0.7.1 # NOTE: 已停止维护
qcloudsms-py: 0.1.4 # NOTE: 已停止维护, 不适配py3.9, 需修改源码

beautifulsoup4: 4.11.1
colorama: 0.4.4
coverage: 6.3.2
djangorestframework: 3.13.1
django-compressor: 3.1
django-cors-headers: 3.11.0
django-cors-middleware: 1.5.0
django-debug-toolbar: 3.2.4
django-filter: 21.1
django-import-export: 2.8.0
django-pure-pagination: 0.3.0
django-recaptcha: 3.0.0
django-redis: 5.2.0
django-user-agents: 0.4.0
fabric: 2.7.0
faker: 13.3.4
fake-useragent: 0.1.11
gunicorn: 20.1.0
ipython: 8.2.0
jieba: 0.42.1
lxml: 4.8.0  # 用作bs4的解析器
Markdown: 3.3.6
moviepy: 1.0.3
mysqlclient: 2.1.0
mysql-to-sqlite3: 1.4.12
numpy: 1.22.3
pandas: 1.4.2
Pillow: 9.1.0
pipdeptree: 2.2.1
pydub: 0.25.1
pymemcache: 3.5.2
python-dotenv: 0.20.0
redis: 4.2.1
requests: 2.27.1
selenium: 4.1.3
sh: 1.14.2
SpeechRecognition: 3.8.1  # 语音识别(推荐直接选用谷歌的引擎)
sqlite3-to-mysql: 1.4.15
webdriver-manager: 3.5.4
Whoosh: 2.7.4
xlrd: 2.0.1
xlwt: 1.3.0
